M48
; DRILL file {KiCad (6.0.1)} date Mon Feb 14 12:00:38 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-14T12:00:38-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X59.54Y-130.49
X61.04Y-112.39
X96.44Y-112.39
X97.94Y-130.49
T2
X40.64Y-93.472
X91.948Y-82.296
T0
M30
